/**
 * Identity & Access — application ports.
 *
 * Ports are pure interfaces; adapters live in `infrastructure/`
 * (ADR-0016). Application services depend only on ports — never on
 * concrete adapters or framework SDKs.
 *
 * This is the published interface other contexts may consume.
 */

import type { RefreshToken } from '../domain/refresh-token';
import type { Tenant } from '../domain/tenant';
import type { User } from '../domain/user';
import type {
  AccessTokenClaims,
  Email,
  PasswordHash,
  RefreshTokenId,
  TenantId,
  UserId,
} from '../domain/value-objects';
import type { IdentityDomainEvent } from '../domain/events';

// ---------------------------------------------------------------------------
// Repository ports (docs/ddd/10-repositories.md)
// ---------------------------------------------------------------------------

export interface UserRepository {
  findById(id: UserId): Promise<User | null>;
  findByEmail(tenantId: TenantId, email: Email): Promise<User | null>;
  /**
   * Save the aggregate; throws AggregateVersionConflict on optimistic
   * lock failure. The expected version is User.version *before* the
   * mutation (i.e. callers pass `user.version - 1` when saving after a
   * mutation, or simply `user.version` when saving an unmodified
   * aggregate). Implementations enforce this strictly.
   */
  save(user: User, expectedVersion: number): Promise<void>;
  delete(id: UserId): Promise<void>;
}

export interface TenantRepository {
  findById(id: TenantId): Promise<Tenant | null>;
  save(tenant: Tenant, expectedVersion: number): Promise<void>;
}

export interface RefreshTokenRepository {
  findActive(tokenId: RefreshTokenId): Promise<RefreshToken | null>;
  /** Atomically rotate `prev` (mark rotated) and persist `next`. */
  rotate(prev: RefreshToken, next: RefreshToken): Promise<void>;
  revoke(tokenId: RefreshTokenId): Promise<void>;
  /** Persist a freshly issued token (no predecessor). */
  put(token: RefreshToken): Promise<void>;
}

// ---------------------------------------------------------------------------
// Adapter ports — pure-function shapes the domain depends on.
// Concrete implementations (bcrypt, jsonwebtoken, ULID lib) live in
// infrastructure/.
// ---------------------------------------------------------------------------

export interface PasswordHasher {
  /** Hash a plaintext password, returning a wrapped value. */
  hash(plaintext: string): Promise<PasswordHash>;
  /** Constant-time check that `plaintext` matches the stored hash. */
  verify(plaintext: string, hash: PasswordHash): Promise<boolean>;
}

export interface AccessTokenSigner {
  sign(claims: AccessTokenClaims): Promise<string>;
  verify(jwt: string): Promise<AccessTokenClaims>;
}

export interface IdGenerator {
  /** Generate a new ULID-shaped identifier. */
  newId(): string;
}

export interface Clock {
  now(): Date;
}

export interface DomainEventPublisher {
  /**
   * Publish events generated by an aggregate within the same
   * transactional unit of work as the aggregate save. The transactional-
   * outbox adapter (ADR-0012) is the canonical implementation.
   */
  publish(events: ReadonlyArray<IdentityDomainEvent>): Promise<void>;
}

// ---------------------------------------------------------------------------
// Result types — application services return Result rather than throwing
// for expected failure paths (docs/ddd/13-tactical-patterns.md).
// ---------------------------------------------------------------------------

export type Result<Ok, Err> =
  | { readonly ok: true; readonly value: Ok }
  | { readonly ok: false; readonly error: Err };

export const Result = {
  ok<Ok>(value: Ok): Result<Ok, never> {
    return { ok: true, value };
  },
  err<Err>(error: Err): Result<never, Err> {
    return { ok: false, error };
  },
};

export type ApplicationError =
  | { kind: 'InputInvalid'; field: string; reason: string }
  | { kind: 'Unauthorised' }
  | { kind: 'Forbidden'; reason: string }
  | { kind: 'NotFound'; resource: string }
  | { kind: 'Conflict'; reason: string };
